In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data/cleaned_email_sms_data.csv')

In [3]:
df

      Unnamed: 0  label                                            message
0              0      0  Go until jurong point, crazy.. Available only ...
1              1      0                      Ok lar... Joking wif u oni...
2              2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3              3      0  U dun say so early hor... U c already then say...
4              4      0  Nah I don't think he goes to usf, he lives aro...
...          ...    ...                                                ...
5567        5567      1  This is the 2nd time we have tried 2 contact u...
5568        5568      0              Will Ì_ b going to esplanade fr home?
5569        5569      0  Pity, * was in mood for that. So...any other s...
5570        5570      0  The guy did some bitching but I acted like i'd...
5571        5571      0                         Rofl. Its true to its name

[5572 rows x 3 columns]

In [4]:
df.drop('Unnamed: 0',axis =1, inplace =True)

In [5]:
df

      label                                            message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567      1  This is the 2nd time we have tried 2 contact u...
5568      0              Will Ì_ b going to esplanade fr home?
5569      0  Pity, * was in mood for that. So...any other s...
5570      0  The guy did some bitching but I acted like i'd...
5571      0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    df['message'], df['label'], test_size=0.2, random_state=42
)

### Converts raw text into vectors so the model can understand

In [7]:
tfidf = TfidfVectorizer(max_features=3000)
X_train_vec = tfidf.fit_transform(X_train)
X_test_vec  = tfidf.transform(X_test)

#### build and train model

In [8]:
model = MultinomialNB()
model.fit(X_train_vec, y_train)

MultinomialNB()

### Prediction and evaluation

In [12]:
y_pred = model.predict(X_test_vec)
train_pred = model.predict(X_train_vec)

In [15]:
print(f"Train Accuracy: {accuracy_score(y_train,train_pred)}")
print(f"Test Accuracy: {accuracy_score(y_test,y_pred)}")

Train Accuracy: 0.9831725375813327
Test Accuracy: 0.9739910313901345

In [16]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['Ham', 'Spam']))

Classification Report:
              precision    recall  f1-score   support

         Ham       0.97      1.00      0.99       965
        Spam       1.00      0.81      0.89       150

    accuracy                           0.97      1115
   macro avg       0.99      0.90      0.94      1115
weighted avg       0.97      0.97      0.97      1115

#### Testing on new data

In [23]:
def predict(text):
    vec = tfidf.transform([text])
    result = model.predict(vec)[0]
    return "SPAM" if result == 1 else "HAM"
 
print("\n── Sample Predictions ──")
print(predict("Congratulations! You won a free iPhone. Click now!"))  # SPAM
print(predict("Hey, are we meeting for lunch tomorrow?"))              # HAM
print(predict("URGENT: Claim your $1000 prize today!"))               # SPAM
print(predict("Please review the attached report."))   
print(predict("URGENT: Claim your $1000 prize today!"))

── Sample Predictions ──
SPAM
HAM
SPAM
HAM
SPAM